version: "3.9"
services:
  react:
    container_name: dbms_algos_frontend
    build:
      context: ./frontend
    environment:
      VITE_DBMS_ALGOS_BACKEND_URL: ${DBMS_ALGOS_BACKEND_URL}
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - ${DBMS_ALGOS_FRONTEND_PORT}:3000

  flask:
    container_name: dbms_algos_backend
    build:
      context: ./backend
    env_file: .env
    volumes:
      - ./backend/:/app/backend
    ports:
      - ${DBMS_ALGOS_BACKEND_PORT}:5000

  nginx:
    container_name: dbms_algos_nginx
    depends_on:
      - flask
      - react
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - ${DBMS_ALGOS_NGINX_PORT}:80
